//
// Created by Mikhail on 02.05.2022.
//

#ifndef COMPUTER_GRAPHICS_SUPPORT_TEXTURE_LOADER_HPP_
#define COMPUTER_GRAPHICS_SUPPORT_TEXTURE_LOADER_HPP_

#endif //COMPUTER_GRAPHICS_SUPPORT_TEXTURE_LOADER_HPP_
